# Generated by Django 5.2 on 2025-05-07 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='chai/')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Masala'), ('GR', 'Ginger'), ('BL', 'Black Tea'), ('LI', 'Lemon Tea')], max_length=50)),
            ],
        ),
    ]
